//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parqueo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parqueodbEntities6 : DbContext
    {
        public parqueodbEntities6()
            : base("name=parqueodbEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boletaPago1> boletaPago1 { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<boletaPago> boletaPago { get; set; }
    }
}
