//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parqueo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int NoVehiculo { get; set; }
        public string Placa { get; set; }
    }
}
